version: '3'

services:
  time-series-analyzer:
    build: .
    ports:
      - "7050:7050"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 8G
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=7050
